openapi: 3.1.0
info:
  title: Blog Engine API
  version: 0.1.0
  description: API for managing Astro blog sites

servers:
  - url: http://localhost:8080
    description: Local development

paths:
  /healthz:
    get:
      summary: Health check (K8s compatible)
      operationId: getHealthz
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    # Standard envelope wrapper
    Envelope:
      type: object
      required:
        - data
        - meta
      properties:
        data:
          description: Response payload
        meta:
          $ref: '#/components/schemas/Meta'

    Meta:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        requestId:
          type: string
          format: uuid
        version:
          type: string
        serverName:
          type: string
          enum: [ backend-node, backend-rust ]

    # Health endpoint response
    HealthData:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]

    HealthResponse:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/HealthData'

    # RFC 7807 Problem Details
    ProblemDetails:
      type: object
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          description: URI reference identifying the problem type
          example: https://api.example.com/problems/not-found
        title:
          type: string
          description: Short human-readable summary
          example: Resource Not Found
        status:
          type: integer
          description: HTTP status code
          example: 404
        detail:
          type: string
          description: Human-readable explanation specific to this occurrence
          example: The requested blog site 'my-blog' was not found
        instance:
          type: string
          format: uri
          description: URI reference identifying the specific occurrence
          example: /api/sites/my-blog
