openapi: 3.1.0
info:
  title: Blog Engine API
  description: API for managing Astro blog sites
  license:
    name: ''
  version: 0.1.0
paths:
  /healthz:
    get:
      tags: []
      operationId: healthz
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelop'
components:
  schemas:
    Envelop:
      type: object
      required:
        - data
        - meta
      properties:
        data:
          $ref: '#/components/schemas/HealthData'
        meta:
          $ref: '#/components/schemas/Meta'
    HealthData:
      type: object
      required:
        - status
        - version
      properties:
        status:
          $ref: '#/components/schemas/HealthStatus'
        version:
          type: string
    HealthStatus:
      type: string
      enum:
        - healthy
    Meta:
      type: object
      required:
        - timestamp
        - requestId
        - version
        - serverName
      properties:
        requestId:
          type: string
        serverName:
          $ref: '#/components/schemas/MetaServerName'
        timestamp:
          type: string
        version:
          type: string
    MetaServerName:
      type: string
      enum:
        - backend-node
        - backend-rust
