minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@sveltejs/kit"
  - "@sveltejs/adapter-static"
blockExoticSubdeps: true
allowBuilds:
  sharp: true
  esbuild: true
onlyBuiltDependencies:
  - esbuild
  - sharp
