# SvelteKit frontend with Rust backend (sweet spot combo)
# Usage: podman compose -f compose.yaml -f compose.backend-rust.yaml -f compose.frontend-svelte.yaml up
#
# Port scheme:
#   - Rust backend:       8080
#   - SvelteKit frontend: 3000
#   - Astro server:       4321 (from base compose.yaml)

services:
  frontend-svelte:
    build:
      context: ./admin-cms-app/frontend-svelte
      dockerfile: Dockerfile.dev
    networks:
      - blog-net
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_BACKEND_URL=http://localhost:8080
    volumes:
      - ./admin-cms-app/frontend-svelte/src:/app/src:ro
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
