name: blog-engine-prod

networks:
  blog-net:
    driver: bridge

volumes:
  astro-sites:

services:
  astro-server:
    build:
      context: ./astro-server
      dockerfile: Dockerfile
    networks:
      - blog-net
    volumes:
      - astro-sites:/app/astro-sites
    ports:
      - '4321:4321'

  backend-rust:
    profiles: [rust]
    build:
      context: ./admin-cms-app/backend-rust
      dockerfile: Dockerfile.prod
    networks:
      - blog-net
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD-SHELL', 'curl -sf http://127.0.0.1:8080/healthz || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3

  backend-node:
    profiles: [node]
    build:
      context: ./admin-cms-app/backend-node
      dockerfile: Dockerfile.prod
    networks:
      - blog-net
    ports:
      - '8081:8080'
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://127.0.0.1:8080/healthz']
      interval: 10s
      timeout: 5s
      retries: 3

  frontend-svelte:
    profiles: [svelte]
    build:
      context: ./admin-cms-app/frontend-svelte
      dockerfile: Dockerfile.prod
      args:
        - PUBLIC_API_BACKEND_URL=http://localhost:8080
    networks:
      - blog-net
    ports:
      - '3000:80'
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://127.0.0.1:80']
      interval: 10s
      timeout: 5s
      retries: 3

  frontend-react:
    profiles: [react]
    build:
      context: ./admin-cms-app/frontend-react
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_BACKEND_URL=http://localhost:8081
    networks:
      - blog-net
    ports:
      - '3001:80'
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://127.0.0.1:80']
      interval: 10s
      timeout: 5s
      retries: 3
