services:
  backend:
    build:
      context: ./admin-cms-app/backend-rust
      dockerfile: Dockerfile.dev
    networks:
      - blog-net
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:8080/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

