// This file has been generated by Specta. DO NOT EDIT.

export type WsMessage = { type: "Command"; payload: Command } | { type: "Event"; payload: Event }

/**
 * A site as the frontend sees it: identity plus current FSM state.
 */
export type SiteView = { slug: string; name: string; state: SiteState }

/**
 * Lean envelope: timestamp + correlation id + flattened message. Commands
 * carry a client-generated `correlation_id`; error events echo it back so the
 * client can match failures to requests.
 */
export type WsEnvelope = ({ type: "Command"; payload: Command } | { type: "Event"; payload: Event }) & { unix_timestamp_us: number; correlation_id: string }

/**
 * Lifecycle of a managed Astro site. Transitions live in `fsm::site`.
 */
export type SiteState = { type: "Creating" } | { type: "Ready" } | { type: "Building" } | { type: "BuildFailed"; payload: { reason: string } } | { type: "Deleting" }

export type LogStream = "Stdout" | "Stderr"

/**
 * Client → server messages.
 */
export type Command = { type: "CreateSite"; payload: { name: string; slug: string } } | { type: "BuildSite"; payload: { slug: string } } | { type: "StartPreview"; payload: { slug: string } } | { type: "StopPreview" } | { type: "DeleteSite"; payload: { slug: string } } | { type: "Ping" }

export type ErrorCode = "SiteNotFound" | "SiteAlreadyExists" | "InvalidTransition" | "BuildFailed" | "PreviewTimeout" | "Internal"

/**
 * The preview as the frontend sees it. `slug` says which site is previewed;
 * `url` is set only while `Running`.
 */
export type PreviewView = { state: PreviewState; slug: string | null; url: string | null }

/**
 * Server → client messages. `Snapshot` is sent on every connect — reconnect
 * strategy is a fresh snapshot, never event replay.
 */
export type Event = { type: "Snapshot"; payload: { sites: SiteView[]; preview: PreviewView } } | { type: "SiteChanged"; payload: SiteView } | { type: "SiteRemoved"; payload: { slug: string } } | { type: "PreviewChanged"; payload: PreviewView } | { type: "BuildLog"; payload: { slug: string; stream: LogStream; data: string } } | { type: "Error"; payload: { code: ErrorCode; message: string; correlation_id: string | null } } | { type: "Pong" }

/**
 * Lifecycle of the (single) Astro dev-server preview. Transitions live in
 * `fsm::preview`. `Starting` covers the TCP readiness poll window.
 */
export type PreviewState = { type: "Stopped" } | { type: "Starting" } | { type: "Running" } | { type: "Stopping" } | { type: "Failed"; payload: { reason: string } }

