FROM rust:slim-trixie

RUN apt-get update && apt-get install -y curl pkg-config libssl-dev git && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch
RUN npm config set fund false && npm upgrade -g npm && npm install -g pnpm && pnpm --version

WORKDIR /app
COPY Cargo.toml Cargo.lock*

RUN cd app && cargo build || true
RUN rm -rf backend/src

COPY backend/src backend/src

WORKDIR /workspace/backend

EXPOSE [8080, 4321]

CMD cargo watch -x 'run'
