/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Blog Engine API
 * API for managing Astro blog sites
 * OpenAPI spec version: 0.1.0
 */
import { createQuery } from "@tanstack/svelte-query";
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
} from "@tanstack/svelte-query";

import { fetchWithServerUrl } from "./lib/api/fetch-with-base-url.js";
export type MetaServerName =
  (typeof MetaServerName)[keyof typeof MetaServerName];

export const MetaServerName = {
  "backend-node": "backend-node",
  "backend-rust": "backend-rust",
} as const;

export interface Meta {
  timestamp?: string;
  requestId?: string;
  version?: string;
  serverName?: MetaServerName;
}

export interface Envelope {
  /** Response payload */
  data: unknown;
  meta: Meta;
}

export type HealthDataStatus =
  (typeof HealthDataStatus)[keyof typeof HealthDataStatus];

export const HealthDataStatus = {
  healthy: "healthy",
  degraded: "degraded",
  unhealthy: "unhealthy",
} as const;

export interface HealthData {
  status: HealthDataStatus;
}

export type HealthResponse = Envelope & {
  data?: HealthData;
};

export interface ProblemDetails {
  /** URI reference identifying the problem type */
  type: string;
  /** Short human-readable summary */
  title: string;
  /** HTTP status code */
  status: number;
  /** Human-readable explanation specific to this occurrence */
  detail?: string;
  /** URI reference identifying the specific occurrence */
  instance?: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check (K8s compatible)
 */
export type getHealthzResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type getHealthzResponseSuccess = getHealthzResponse200 & {
  headers: Headers;
};
export type getHealthzResponse = getHealthzResponseSuccess;

export const getGetHealthzUrl = () => {
  return `/healthz`;
};

export const getHealthz = async (
  options?: RequestInit,
): Promise<getHealthzResponse> => {
  return fetchWithServerUrl<getHealthzResponse>(getGetHealthzUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetHealthzQueryKey = () => {
  return [`/healthz`] as const;
};

export const getGetHealthzQueryOptions = <
  TData = Awaited<ReturnType<typeof getHealthz>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    CreateQueryOptions<Awaited<ReturnType<typeof getHealthz>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetchWithServerUrl>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHealthzQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealthz>>> = ({
    signal,
  }) => getHealthz({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof getHealthz>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHealthzQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHealthz>>
>;
export type GetHealthzQueryError = unknown;

/**
 * @summary Health check (K8s compatible)
 */

export function createGetHealthz<
  TData = Awaited<ReturnType<typeof getHealthz>>,
  TError = unknown,
>(
  options?: () => {
    query?: Partial<
      CreateQueryOptions<Awaited<ReturnType<typeof getHealthz>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchWithServerUrl>;
  },
  queryClient?: () => QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const query = createQuery(
    () => getGetHealthzQueryOptions(options?.()),
    queryClient,
  ) as CreateQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return query;
}
