/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Blog Engine API
 * API for managing Astro blog sites
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { fetchWithBaseUrl } from "./lib/api/fetch-with-base-url";
/**
 * Request body for creating a new site.
 */
export interface CreateSiteRequest {
  name: string;
  slug: string;
}

export type HealthStatus = (typeof HealthStatus)[keyof typeof HealthStatus];

export const HealthStatus = {
  healthy: "healthy",
} as const;

export interface HealthData {
  status: HealthStatus;
  version: string;
}

export type MetaServerName =
  (typeof MetaServerName)[keyof typeof MetaServerName];

export const MetaServerName = {
  "backend-node": "backend-node",
  "backend-rust": "backend-rust",
} as const;

export interface Meta {
  requestId: string;
  serverName: MetaServerName;
  timestamp: string;
  version: string;
}

/**
 * Response envelope for the health endpoint.
 */
export interface HealthResponse {
  data: HealthData;
  meta: Meta;
}

/**
 * A single Astro site managed by the CMS.
 */
export interface SiteData {
  gitUrl: string;
  name: string;
  /** @nullable */
  previewUrl?: string | null;
  slug: string;
}

/**
 * Response envelope for a list of sites.
 */
export interface SiteListResponse {
  data: SiteData[];
  meta: Meta;
}

/**
 * Response envelope for a single site.
 */
export interface SiteResponse {
  data: SiteData;
  meta: Meta;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type healthzResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type healthzResponseSuccess = healthzResponse200 & {
  headers: Headers;
};
export type healthzResponse = healthzResponseSuccess;

export const getHealthzUrl = () => {
  return `/healthz`;
};

export const healthz = async (
  options?: RequestInit,
): Promise<healthzResponse> => {
  return fetchWithBaseUrl<healthzResponse>(getHealthzUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthzQueryKey = () => {
  return [`/healthz`] as const;
};

export const getHealthzQueryOptions = <
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetchWithBaseUrl>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthzQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthz>>> = ({
    signal,
  }) => healthz({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthz>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthzQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthz>>
>;
export type HealthzQueryError = unknown;

export function useHealthz<
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthz>>,
          TError,
          Awaited<ReturnType<typeof healthz>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthz<
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthz>>,
          TError,
          Awaited<ReturnType<typeof healthz>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthz<
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useHealthz<
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthzQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type stopPreviewResponse204 = {
  data: void;
  status: 204;
};

export type stopPreviewResponseSuccess = stopPreviewResponse204 & {
  headers: Headers;
};
export type stopPreviewResponse = stopPreviewResponseSuccess;

export const getStopPreviewUrl = () => {
  return `/preview`;
};

export const stopPreview = async (
  options?: RequestInit,
): Promise<stopPreviewResponse> => {
  return fetchWithBaseUrl<stopPreviewResponse>(getStopPreviewUrl(), {
    ...options,
    method: "DELETE",
  });
};

export const getStopPreviewMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof stopPreview>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof fetchWithBaseUrl>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof stopPreview>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["stopPreview"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof stopPreview>>,
    void
  > = () => {
    return stopPreview(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StopPreviewMutationResult = NonNullable<
  Awaited<ReturnType<typeof stopPreview>>
>;

export type StopPreviewMutationError = unknown;

export const useStopPreview = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof stopPreview>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof stopPreview>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getStopPreviewMutationOptions(options), queryClient);
};

export type listSitesResponse200 = {
  data: SiteListResponse;
  status: 200;
};

export type listSitesResponseSuccess = listSitesResponse200 & {
  headers: Headers;
};
export type listSitesResponse = listSitesResponseSuccess;

export const getListSitesUrl = () => {
  return `/sites`;
};

export const listSites = async (
  options?: RequestInit,
): Promise<listSitesResponse> => {
  return fetchWithBaseUrl<listSitesResponse>(getListSitesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListSitesQueryKey = () => {
  return [`/sites`] as const;
};

export const getListSitesQueryOptions = <
  TData = Awaited<ReturnType<typeof listSites>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listSites>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetchWithBaseUrl>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListSitesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listSites>>> = ({
    signal,
  }) => listSites({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listSites>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListSitesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listSites>>
>;
export type ListSitesQueryError = unknown;

export function useListSites<
  TData = Awaited<ReturnType<typeof listSites>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listSites>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSites>>,
          TError,
          Awaited<ReturnType<typeof listSites>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSites<
  TData = Awaited<ReturnType<typeof listSites>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listSites>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSites>>,
          TError,
          Awaited<ReturnType<typeof listSites>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSites<
  TData = Awaited<ReturnType<typeof listSites>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listSites>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListSites<
  TData = Awaited<ReturnType<typeof listSites>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listSites>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListSitesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type createSiteResponse201 = {
  data: SiteResponse;
  status: 201;
};

export type createSiteResponse400 = {
  data: void;
  status: 400;
};

export type createSiteResponse500 = {
  data: void;
  status: 500;
};

export type createSiteResponseSuccess = createSiteResponse201 & {
  headers: Headers;
};
export type createSiteResponseError = (
  | createSiteResponse400
  | createSiteResponse500
) & {
  headers: Headers;
};

export type createSiteResponse =
  | createSiteResponseSuccess
  | createSiteResponseError;

export const getCreateSiteUrl = () => {
  return `/sites`;
};

export const createSite = async (
  createSiteRequest: CreateSiteRequest,
  options?: RequestInit,
): Promise<createSiteResponse> => {
  return fetchWithBaseUrl<createSiteResponse>(getCreateSiteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createSiteRequest),
  });
};

export const getCreateSiteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSite>>,
    TError,
    { data: CreateSiteRequest },
    TContext
  >;
  request?: SecondParameter<typeof fetchWithBaseUrl>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSite>>,
  TError,
  { data: CreateSiteRequest },
  TContext
> => {
  const mutationKey = ["createSite"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSite>>,
    { data: CreateSiteRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createSite(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSiteMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSite>>
>;
export type CreateSiteMutationBody = CreateSiteRequest;
export type CreateSiteMutationError = void;

export const useCreateSite = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSite>>,
      TError,
      { data: CreateSiteRequest },
      TContext
    >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSite>>,
  TError,
  { data: CreateSiteRequest },
  TContext
> => {
  return useMutation(getCreateSiteMutationOptions(options), queryClient);
};

export type previewSiteResponse200 = {
  data: SiteResponse;
  status: 200;
};

export type previewSiteResponse404 = {
  data: void;
  status: 404;
};

export type previewSiteResponse500 = {
  data: void;
  status: 500;
};

export type previewSiteResponseSuccess = previewSiteResponse200 & {
  headers: Headers;
};
export type previewSiteResponseError = (
  | previewSiteResponse404
  | previewSiteResponse500
) & {
  headers: Headers;
};

export type previewSiteResponse =
  | previewSiteResponseSuccess
  | previewSiteResponseError;

export const getPreviewSiteUrl = (slug: string) => {
  return `/sites/${slug}/preview`;
};

export const previewSite = async (
  slug: string,
  options?: RequestInit,
): Promise<previewSiteResponse> => {
  return fetchWithBaseUrl<previewSiteResponse>(getPreviewSiteUrl(slug), {
    ...options,
    method: "POST",
  });
};

export const getPreviewSiteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof previewSite>>,
    TError,
    { slug: string },
    TContext
  >;
  request?: SecondParameter<typeof fetchWithBaseUrl>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof previewSite>>,
  TError,
  { slug: string },
  TContext
> => {
  const mutationKey = ["previewSite"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof previewSite>>,
    { slug: string }
  > = (props) => {
    const { slug } = props ?? {};

    return previewSite(slug, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PreviewSiteMutationResult = NonNullable<
  Awaited<ReturnType<typeof previewSite>>
>;

export type PreviewSiteMutationError = void;

export const usePreviewSite = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof previewSite>>,
      TError,
      { slug: string },
      TContext
    >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof previewSite>>,
  TError,
  { slug: string },
  TContext
> => {
  return useMutation(getPreviewSiteMutationOptions(options), queryClient);
};
