/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Blog Engine API
 * API for managing Astro blog sites
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { fetchWithBaseUrl } from "./lib/api/fetch-with-base-url";
export type HealthStatus = (typeof HealthStatus)[keyof typeof HealthStatus];

export const HealthStatus = {
  healthy: "healthy",
} as const;

export interface HealthData {
  status: HealthStatus;
  version: string;
}

export type MetaServerName =
  (typeof MetaServerName)[keyof typeof MetaServerName];

export const MetaServerName = {
  "backend-node": "backend-node",
  "backend-rust": "backend-rust",
} as const;

export interface Meta {
  requestId: string;
  serverName: MetaServerName;
  timestamp: string;
  version: string;
}

export interface Envelop {
  data: HealthData;
  meta: Meta;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type healthzResponse200 = {
  data: Envelop;
  status: 200;
};

export type healthzResponseSuccess = healthzResponse200 & {
  headers: Headers;
};
export type healthzResponse = healthzResponseSuccess;

export const getHealthzUrl = () => {
  return `/healthz`;
};

export const healthz = async (
  options?: RequestInit,
): Promise<healthzResponse> => {
  return fetchWithBaseUrl<healthzResponse>(getHealthzUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthzQueryKey = () => {
  return [`/healthz`] as const;
};

export const getHealthzQueryOptions = <
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetchWithBaseUrl>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthzQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthz>>> = ({
    signal,
  }) => healthz({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthz>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthzQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthz>>
>;
export type HealthzQueryError = unknown;

export function useHealthz<
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthz>>,
          TError,
          Awaited<ReturnType<typeof healthz>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthz<
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthz>>,
          TError,
          Awaited<ReturnType<typeof healthz>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthz<
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useHealthz<
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchWithBaseUrl>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthzQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
