/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_sites"];
        put?: never;
        post: operations["create_site"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for creating a new site. */
        CreateSiteRequest: {
            name: string;
            slug: string;
        };
        HealthData: {
            status: components["schemas"]["HealthStatus"];
            version: string;
        };
        /** @description Response envelope for the health endpoint. */
        HealthResponse: {
            data: components["schemas"]["HealthData"];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        HealthStatus: "healthy";
        Meta: {
            requestId: string;
            serverName: components["schemas"]["MetaServerName"];
            timestamp: string;
            version: string;
        };
        /** @enum {string} */
        MetaServerName: "backend-node" | "backend-rust";
        /** @description A single Astro site managed by the CMS. */
        SiteData: {
            gitUrl: string;
            name: string;
            slug: string;
        };
        /** @description Response envelope for a list of sites. */
        SiteListResponse: {
            data: components["schemas"]["SiteData"][];
            meta: components["schemas"]["Meta"];
        };
        /** @description Response envelope for a single site. */
        SiteResponse: {
            data: components["schemas"]["SiteData"];
            meta: components["schemas"]["Meta"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_sites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all sites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteListResponse"];
                };
            };
        };
    };
    create_site: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSiteRequest"];
            };
        };
        responses: {
            /** @description Site created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Management API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
