/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelop: {
            data: components["schemas"]["HealthData"];
            meta: components["schemas"]["Meta"];
        };
        HealthData: {
            status: components["schemas"]["HealthStatus"];
            version: string;
        };
        /** @enum {string} */
        HealthStatus: "healthy";
        Meta: {
            requestId: string;
            serverName: components["schemas"]["MetaServerName"];
            timestamp: string;
            version: string;
        };
        /** @enum {string} */
        MetaServerName: "backend-node" | "backend-rust";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelop"];
                };
            };
        };
    };
}
